const BASE_URL = process.env.NEXT_PUBLIC_BASE_URL;

export const DASHBOARD_API_URL = BASE_URL + "/api/dashboard"
export const BRANCH_API_URL = BASE_URL + "/api/branches"
export const APPOINTMENTS_API_URL = BASE_URL + "/api/appointments"
export const APPOINTMENT_SERVICES_API_URL = BASE_URL + "/api/appointment-services"
export const BOOKINGS_API_URL = BASE_URL + "/api/bookings"
export const SERVICES_API_URL = BASE_URL + "/api/services"
export const CATEGORIES_API_URL = BASE_URL + "/api/categories"
export const SUBCATEGORIES_API_URL = BASE_URL + "/api/sub-categories"
export const EMPLOYEES_API_URL = BASE_URL + "/api/employees"
export const GROUP_API_URL = BASE_URL + "/api/groups"
export const CUSTOMERS_API_URL = BASE_URL + "/api/customers"
export const ASSETS_API_URL = BASE_URL + "/api/assets"
export const ASSET_TYPES_API_URL = BASE_URL + "/api/asset-types"
export const SHIFTS_API_URL = BASE_URL + "/api/shifts"
export const COUPONS_API_URL = BASE_URL + "/api/coupons"
export const VOUCHERS_API_URL = BASE_URL + "/api/vouchers"
export const VOUCHER_PURCHASED_API_URL = BASE_URL + "/api/voucher-purchased"
export const SETTINGS_API_URL = BASE_URL + "/api/settings"
export const ROSTER_API_URL = BASE_URL + "/api/roster"
export const TRANSFERRED_EMPLOYEES_API_URL = BASE_URL + "/api/transferred-employees"
export const COMMISSIONS_API_URL = BASE_URL + "/api/commissions"
export const ROLES_API_URL = BASE_URL + "/api/roles"


